#mysql
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3307/hello?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 5
        min-idle: 5
        max-idle: 5
        initial-size: 5

mybatis:
    mapper-locations: classpath:mapper/*.xml
